import { Router } from 'express';
import { afipRouter } from './afip.routes';
import { anticiposProveedorRouter } from './anticiposProveedor.routes';
import { authRouter } from './auth.routes';
import { catalogosRouter } from './catalogos.routes';
import { clientesRouter } from './clientes.routes';
import { cotizacionesRouter } from './cotizaciones.routes';
import { cuentaCorrienteRouter } from './cuentaCorriente.routes';
import { documentosRouter } from './documentos.routes';
import { facturasProveedorRouter } from './facturasProveedor.routes';
import { hojasDeRutaRouter } from './hojasDeRuta.routes';
import { logisticaRouter } from './logistica.routes';
import { notasCreditoProveedorRouter } from './notasCreditoProveedor.routes';
import { ordenesEntregaRouter } from './ordenesEntrega.routes';
import { ordenesPagoRouter } from './ordenesPago.routes';
import { productosRouter } from './productos.routes';
import { proveedoresRouter } from './proveedores.routes';
import { recibosRouter } from './recibos.routes';
import { remitosRouter } from './remitos.routes';
import { ventasRouter } from './ventas.routes';

export const apiRouter = Router();

apiRouter.use('/afip', afipRouter);
apiRouter.use('/anticipos-proveedor', anticiposProveedorRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/catalogos', catalogosRouter);
apiRouter.use('/clientes', clientesRouter);
apiRouter.use('/cotizaciones', cotizacionesRouter);
apiRouter.use('/cuenta-corriente', cuentaCorrienteRouter);
apiRouter.use('/documentos', documentosRouter);
apiRouter.use('/facturas-proveedor', facturasProveedorRouter);
apiRouter.use('/hojas-de-ruta', hojasDeRutaRouter);
apiRouter.use('/logistica', logisticaRouter);
apiRouter.use('/notas-credito-proveedor', notasCreditoProveedorRouter);
apiRouter.use('/ordenes-entrega', ordenesEntregaRouter);
apiRouter.use('/ordenes-pago', ordenesPagoRouter);
apiRouter.use('/productos', productosRouter);
apiRouter.use('/proveedores', proveedoresRouter);
apiRouter.use('/recibos', recibosRouter);
apiRouter.use('/remitos', remitosRouter);
apiRouter.use('/ventas', ventasRouter);
